### ISSUE TITLE
Source-map as option

### ISSUE THREAD

**Issue by jimmyadaro** [aadityataparia/uglify-on-save#1]
I'll like to see`--source-map` as package option, because I don't need it.

**Comment by aadityataparia** [comment]
I don't think I get what you mean?

**Comment by aadityataparia** [comment]
You mean to make generating source map as optional?

**Comment by jimmyadaro** [comment]
Yeah, make it optional. Anyway, I forked some time ago your package and removed that option since I never need it: https://github.com/jimmyadaro/minify-on-save
